spring:
    datasource:
        url: jdbc:mariadb://host:port/qt_mate
        driverClassName: org.mariadb.jdbc.Driver
        username: name
        password: pw
    thymeleaf:
        enabled: true
        prefix: classpath:/templates/
        suffix: .html
        cache: false
    security:
        user:
            name: admin
            password: admin
    devtools:
        livereload:
            enabled: true
mybatis:
    type-aliases-package: qt.mate.qt_mate.dto
    mapper-locations: classpath*:mapper/*.xml