spring:
    datasource:
        url: 
        driverClassName: org.mariadb.jdbc.Driver
        username: 
        password: 
    devtools:
        livereload:
            enabled: true
mybatis:
    type-aliases-package: qt.mate.qt_mate.model
    mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:log4j2.yml