spring:
    datasource:
        url: jdbc:mariadb://
        driverClassName: org.mariadb.jdbc.Driver
        username: 
        password: 
    security:
        user:
            name: admin
            password: admin
    devtools:
        livereload:
            enabled: true
mybatis:
    type-aliases-package: qt.mate.qt_mate.model
    mapper-locations: classpath:mapper/*.xml